export const REQUEST_PRODUCTS_LIST = 'REQUEST_PRODUCTS_LIST'
export const REQUEST_PRODUCTS_LIST_SUCCESS = 'REQUEST_PRODUCTS_LIST_SUCCESS'
export const REQUEST_PRODUCTS_LIST_FAIL = 'REQUEST_PRODUCTS_LIST_FAIL'