export const REQUEST_PRODUCTS_LIST = 'REQUEST_PRODUCTS_LIST'
export const REQUEST_PRODUCTS_LIST_SUCCESS = 'REQUEST_PRODUCTS_LIST_SUCCESS'
export const REQUEST_PRODUCTS_LIST_FAIL = 'REQUEST_PRODUCTS_LIST_FAIL'

export const REQUEST_REMOVE_PRODUCT = 'REQUEST_REMOVE_PRODUCT'
export const REQUEST_REMOVE_PRODUCT_SUCCESS = 'REQUEST_REMOVE_PRODUCT_SUCCESS'
export const REQUEST_REMOVE_PRODUCT_FAIL = 'REQUEST_REMOVE_PRODUCT_FAIL'

export const REQUEST_CREATE_PRODUCT = 'REQUEST_CREATE_PRODUCT'
export const REQUEST_CREATE_PRODUCT_SUCCESS = 'REQUEST_CREATE_PRODUCT_SUCCESS'
export const REQUEST_CREATE_PRODUCT_FAIL = 'REQUEST_CREATE_PRODUCT_FAIL'

export const REQUEST_UPDATE_PRODUCT = 'REQUEST_UPDATE_PRODUCT'
export const REQUEST_UPDATE_PRODUCT_SUCCESS = 'REQUEST_UPDATE_PRODUCT_SUCCESS'
export const REQUEST_UPDATE_PRODUCT_FAIL = 'REQUEST_UPDATE_PRODUCT_FAIL'

export const REQUEST_PRODUCT = 'REQUEST_PRODUCT'
export const REQUEST_PRODUCT_SUCCESS = 'REQUEST_PRODUCT_SUCCESS'
export const REQUEST_PRODUCT_FAIL = 'REQUEST_PRODUCT_FAIL'